/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package belajar.kotlin.coroutine

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)

    println("Running in thread: ${Thread.currentThread().name}")
}
