[package]
name = "belajar-rust-redis"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
redis = { version = "0.28.0", features = ["tokio-comp"] }
tokio = { version = "1.43.0", features = ["full"] }
