apiVersion: v1
kind: Service
metadata:
  name: app-tier
  namespace: deployments
  labels:
    app: microservices
spec:
  ports:
  - port: 8080
  selector:
    tier: app
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-tier
  namespace: deployments
  labels:
    app: microservices
    tier: app
spec:
  replicas: 5
  selector:
    matchLabels:
      tier: app
  template:
    metadata:
      labels:
        app: microservices
        tier: app
    spec:
      containers:
      - name: server
        image: lrakai/microservices:server-v1
        ports:
          - containerPort: 8080
        resources:
          # requests:
          #   cpu: 20m
          limits:
            cpu: "1000m"     # 500m = 500 milliCPUs (1/2 CPU)
            memory: "1000Mi" # 128Mi = 128 mebibytes
        env:
          - name: REDIS_URL
            # Environment variable service discovery
            # Naming pattern:
            #   IP address: <all_caps_service_name>_SERVICE_HOST
            #   Port: <all_caps_service_name>_SERVICE_PORT
            #   Named Port: <all_caps_service_name>_SERVICE_PORT_<all_caps_port_name>
            value: redis://$(DATA_TIER_SERVICE_HOST):$(DATA_TIER_SERVICE_PORT_REDIS)
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-tier-secret
                key: password

# kubectl apply -f app-tier.yaml -n deployments