version: "3.8"

volumes:
  postgres-1:
    name: postgres-1

services:
  postgres:
    container_name: postgres_db
    image: postgres:14.13
    restart: always
    ports:
     - "3306:3306"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
     - postgres-1:/var/lib/postgresql/data
