[package]
name = "belajar-rust-database"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
sqlx = { version = "0.8.3", features = ["runtime-tokio", "chrono", "postgres"] }
tokio = { version = "1.42.0", features = ["full"] }
