volumes:
  postgres-data:
    name: postgres-data

services:
  postgres:
    container_name: postgres_db
    image: postgres:14.13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data