volumes:
  redis-data:
    name: redis-data

services:
  redis:
    image: "redis:alpine3.20"
    container_name: "redis_service"
    ports:
      - "6379:6379"  # Expose Redis on port 6379
    volumes:
      - redis-data:/data  # Persist Redis data to a volume
    # command: ["redis-server", "--appendonly", "yes"]  # Enable AOF persistence for durability
