# Get all categories
GET http://localhost:8000/api/categories
X-API-Key: RAHASIA
Accept: application/json

# Create new category 
POST http://localhost:8000/api/categories
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "name": ""
}

# Get category by Id 
GET http://localhost:8000/api/categories/2
X-API-Key: RAHASIA
Accept: application/json

# Update category by id 
PUT http://localhost:8000/api/categories/100
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "name": "Toys"
}

# Delete category by id 
DELETE http://localhost:8000/api/categories/2
X-API-Key: RAHASIA
Accept: application/json
